### ISSUE TITLE
rsg for Kubernetes API

### ISSUE THREAD

**Issue by rajusreenivasan** [mhausenblas/right-size-guide#1]
Team,
We are trying to use rsg cli to test resource allocation of API hosted in Kubernetes. The ingress URL is https://k8s-api.mycompany.com 

command used
`rsg --target test/test --api-path /k8s-api.mycompany.com --api-port 443`

The output is
`Get http://127.0.0.1:443/k8s-api.mycompany.com dial tcp 127.0.0.1:443 connect: connection refused`

Can you please let us know if the tool can be used to analyze the K8S API ingress URL ?

Thanks
Raju Sreenivasan

**Comment by mhausenblas** [comment]
Thanks a lot @rajusreenivasan and this is an excellent suggestion, happy to extend the tool into this direction!

Now, the output you see is expected (in its current implementation) as the `target` is launched in-process and the HTTP API call also is in-process. Technically, there are two Go routines running with one being the `target` binary that is assumed to expose a HTTP API and one that carries out the load testing.

It should be straight-forward to add a, say `--base-url` parameter that defaults to `http://127.0.0.1` and that you can use to point it to an external API.

Does this make sense?

**Comment by mhausenblas** [comment]
Added support for the base URL in [v0.96](https://github.com/mhausenblas/right-size-guide/releases/tag/v0.96). I do note, however, that the results might not be what you'd expect in a real-world setup (since the load is now in the external service rather than in the process itself, which was the intention of the stress test in the first place). Let me know what you think, please.

**Comment by rajusreenivasan** [comment]
Thanks for your response.
Sorry, I could not understand the solution mentioned. Can I confirm that
the current tool cannot be used to find the resource usage of external API
URLs or is there a workaround?

Regards
Raju Sreenivasan

**Comment by mhausenblas** [comment]
The tool measures the resource usage of `--target`.

**Comment by rajusreenivasan** [comment]
"It should be straight-forward to add a, say --base-url parameter that defaults to http://127.0.0.1 and that you can use to point it to an external API. Does this make sense?"
Definitely,  this solution should solve our problem. Thanks for considering our requirement.
