### ISSUE TITLE
rsg for testing Docker API

### ISSUE THREAD

**Issue by rajusreenivasan** [mhausenblas/right-size-guide#2]
We wanted to test the usage of APIs hosted in Kubernetes. I came to know that the feature is not available and the tool can be used to test locally hosted APIs. So I am trying to run a Docker image in my developer machine and test the API using localhost. But it is not working as expected. The steps performed is given below

1) Created Docker image with Python Django image to expose Rest API
2) Started the container in the developer machine
> docker run -p 8090:8080 djangoimage:1.0
Watching for file changes with StartReloader
3) Started duplicate session and verified the API
> curl -i http://127.0.0.1:8090/
Hello World. You are at the index page
4) Executed below rsg command
> rsg --target test/test --api-path / --api-port 8090
Launching test/test for idle state resource usage assessment
Found idle state resource usage. Memory 0 kb CPU: 0 ms
5) The docker is also throwing below error message in the first session
ConnectionResetError: [Error 104] Connection reset by peer

Can you please look into the issue ? Can we use the tool to test Rest API created using Docker containers ?

Thanks
Raju Sreenivasan

**Comment by mhausenblas** [comment]
I'm not sure what you're trying to do here. As per the [docs](https://mhausenblas.info/right-size-guide/usage/) the `--target` needs to be the SOT.

**Comment by rajusreenivasan** [comment]
oh i am sorry. AWS suggested this tool to test the Rest API before deploying to Kubernetes Cluster. I did not read the documentation properly. Thanks for the clarifications
